"use client";
import {useEffect,useMemo,useState} from "react";
import {readStatementFile} from "../../lib/readStatementFile";

type DocumentType="bank_statement"|"credit_card";
type ImportItem={fingerprint:string;date:string;description:string;rawDescription:string;merchantKey:string;nameLearned:boolean;paymentMethod:string;amount:number;category:string;confidence:"high"|"medium"|"low";installmentCurrent:number|null;installmentTotal:number|null;duplicateKind:"already_imported"|"possible_manual"|"within_file"|null;matchedExpenseName:string|null;duplicateReason:string|null};
type ImportPreview={items:ImportItem[];ignoredIncome:number;summary:{transactions:number;duplicates:number;ready:number}};
type InstallmentOverride={current:number|null;total:number|null};
type Props={months:string[];initialMonth?:string;mode?:"all"|"movements"|"credit-card";duePeriodsByMonth?:Record<string,number[]>;onImported?:()=>void|Promise<void>};

const categories=["Alimentação","Transporte","Assinaturas","Saúde","Contas da casa","Moradia","Educação","Dívidas e contratos","Transferência","Outros gastos"];
const BRL=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const monthName=(key:string)=>new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${key}-01T00:00:00Z`)).replace(/^./,character=>character.toUpperCase());

export default function StatementImport({months,initialMonth="",mode="all",duePeriodsByMonth={},onImported}:Props){
 const fixedStatement=mode==="movements",fixedCard=mode==="credit-card",[bankFile,setBankFile]=useState<File|null>(null),[documentType,setDocumentType]=useState<DocumentType>("bank_statement"),[accountName,setAccountName]=useState(""),[targetMonth,setTargetMonth]=useState(initialMonth||months.at(-1)||""),[dueDay,setDueDay]=useState(10),[preview,setPreview]=useState<ImportPreview|null>(null),[selected,setSelected]=useState<Set<string>>(new Set()),[categoryOverrides,setCategoryOverrides]=useState<Record<string,string>>({}),[nameOverrides,setNameOverrides]=useState<Record<string,string>>({}),[installmentOverrides,setInstallmentOverrides]=useState<Record<string,InstallmentOverride>>({}),[importContent,setImportContent]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const configuredPeriods=duePeriodsByMonth[targetMonth]?.length?duePeriodsByMonth[targetMonth]:[10],[targetYear,targetMonthNumber]=targetMonth.split("-").map(Number),daysInTarget=targetYear&&targetMonthNumber?new Date(targetYear,targetMonthNumber,0).getDate():31,cardMode=fixedCard||!fixedStatement&&documentType==="credit_card",activePeriods=useMemo(()=>cardMode?Array.from({length:daysInTarget},(_,index)=>index+1):configuredPeriods,[cardMode,daysInTarget,duePeriodsByMonth,targetMonth]);
 useEffect(()=>{if(initialMonth&&months.includes(initialMonth))setTargetMonth(initialMonth);else if(!months.includes(targetMonth))setTargetMonth(months.at(-1)||"")},[initialMonth,months,targetMonth]);
 useEffect(()=>{if(!activePeriods.includes(dueDay))setDueDay(activePeriods[0])},[activePeriods,dueDay]);
 const activeType:DocumentType=fixedStatement?"bank_statement":fixedCard?"credit_card":documentType,importPayload=(action:"preview"|"commit")=>({action,targetMonth,documentType:activeType,accountName,dueDay:activeType==="credit_card"?dueDay:null,fileName:bankFile?.name||"extrato",content:importContent,selectedFingerprints:[...selected],categoryOverrides,nameOverrides,installmentOverrides});
 const analyze=async()=>{if(!bankFile||!targetMonth)return;setBusy(true);setMessage("");setPreview(null);try{const content=await readStatementFile(bankFile);setImportContent(content);const response=await fetch("/api/imports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...importPayload("preview"),content,fileName:bankFile.name})}),result=await response.json() as ImportPreview&{error?:string};if(!response.ok)throw new Error(result.error||"Não foi possível ler este arquivo.");setPreview(result);setSelected(new Set(result.items.filter(item=>!item.duplicateKind||activeType==="bank_statement"&&item.duplicateKind==="possible_manual").map(item=>item.fingerprint)));setCategoryOverrides(Object.fromEntries(result.items.map(item=>[item.fingerprint,item.category])));setNameOverrides(Object.fromEntries(result.items.map(item=>[item.fingerprint,item.description])));setInstallmentOverrides(Object.fromEntries(result.items.map(item=>[item.fingerprint,{current:item.installmentCurrent,total:item.installmentTotal}])))}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível ler este arquivo.")}finally{setBusy(false)}};
 const commit=async()=>{if(!preview)return;setBusy(true);setMessage("");try{const response=await fetch("/api/imports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(importPayload("commit"))}),result=await response.json() as {error?:string;imported:number;flagged:number;skipped:number};if(!response.ok)throw new Error(result.error||"Não foi possível concluir a importação.");const destination=activeType==="bank_statement"?"em Movimentações":"na agenda de contas";setMessage(`${result.imported} ${result.imported===1?"registro importado":"registros importados"} ${destination}. ${result.flagged?`${result.flagged} possível duplicidade foi enviada para a Leitura Financeira.`:"Nenhuma nova duplicidade ficou pendente."}`);setPreview(null);setBankFile(null);setImportContent("");await onImported?.()}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível concluir a importação.")}finally{setBusy(false)}};
 const toggle=(fingerprint:string)=>setSelected(current=>{const next=new Set(current);if(next.has(fingerprint))next.delete(fingerprint);else next.add(fingerprint);return next}),selectedTotal=useMemo(()=>preview?.items.filter(item=>selected.has(item.fingerprint)).reduce((sum,item)=>sum+item.amount,0)||0,[preview,selected]);
 return <section className={`bankImportPanel ${fixedStatement?"movementImportPanel":""} ${fixedCard?"cardImportPanel":""}`}>
  <div className="bankImportHead"><div><span className="eyebrow">{fixedCard?"CONFERÊNCIA DA FATURA":"CONCILIAÇÃO BANCÁRIA"}</span><h2>{fixedStatement?"Importar extrato bancário":fixedCard?"Importar fatura do cartão":"Importar extrato ou fatura"}</h2><p>{fixedStatement?"Adicione as saídas da conta aqui e revise tudo antes de confirmar.":fixedCard?"Confira cada compra, data, valor e parcela antes de enviar a fatura para a visão mensal.":"Extratos alimentam Movimentações. Faturas de cartão alimentam a agenda de contas que ainda serão pagas."}</p></div><span className="safeImportBadge">Nada entra sem sua revisão</span></div>
  <div className="importSteps"><div><b>1</b><span>Envie OFX, CSV ou PDF</span></div><div><b>2</b><span>Confira nomes e duplicidades</span></div><div><b>3</b><span>Confirme a importação</span></div></div>
  <div className={`importForm ${fixedStatement?"statementOnly":""} ${fixedCard?"cardOnly":""}`}>
   {!fixedStatement&&!fixedCard&&<label>Tipo de documento<select value={documentType} onChange={event=>{setDocumentType(event.target.value as DocumentType);setPreview(null)}}><option value="bank_statement">Extrato bancário</option><option value="credit_card">Fatura de cartão</option></select></label>}
   <label>{fixedCard?"Nome do cartão":"Conta ou cartão"}<input placeholder={fixedCard?"Ex.: Nubank final 1234":"Ex.: Nubank principal"} value={accountName} onChange={event=>setAccountName(event.target.value)}/></label>
   <label>Mês de destino<select value={targetMonth} onChange={event=>{setTargetMonth(event.target.value);setPreview(null)}}>{months.map(month=><option key={month} value={month}>{monthName(month)}</option>)}</select></label>
   {activeType==="credit_card"&&<label>Vencimento da fatura<select value={dueDay} onChange={event=>{setDueDay(Number(event.target.value));setPreview(null)}}>{activePeriods.map(day=><option value={day} key={day}>Dia {day}</option>)}</select></label>}
   <label className={`statementFile ${bankFile?"hasFile":""}`}><span>{bankFile?bankFile.name:"Selecionar OFX, CSV ou PDF"}</span><input type="file" accept=".ofx,.csv,.pdf,text/csv,application/x-ofx,application/pdf" onChange={event=>{setBankFile(event.target.files?.[0]||null);setPreview(null)}}/></label>
   <button className="analyzeStatement" disabled={!bankFile||!targetMonth||busy} onClick={analyze}>{busy&&!preview?"Analisando…":"Analisar arquivo"}</button>
  </div>
  <p className="importPrivacy">PDFs com texto selecionável também são aceitos. Confira os nomes sugeridos: quando você corrige um estabelecimento, o Shift Zone memoriza sua escolha.</p>
  {message&&<div className="importMessage" role="status">{message}</div>}
  {preview&&<div className="importReview">
   <div className="reviewSummary"><div><span>{activeType==="credit_card"?"Compras encontradas":"Saídas encontradas"}</span><strong>{preview.summary.transactions}</strong></div><div><span>Prontas para importar</span><strong>{preview.summary.ready}</strong></div><div className={preview.summary.duplicates?"warn":""}><span>Possíveis duplicidades</span><strong>{preview.summary.duplicates}</strong></div><div><span>{activeType==="credit_card"?"Créditos ignorados":"Entradas não importadas"}</span><strong>{preview.ignoredIncome}</strong></div></div>
   {preview.summary.duplicates>0&&<div className="duplicateNotice"><b>Encontramos lançamentos que merecem análise.</b><span>{activeType==="bank_statement"?"Eles podem entrar em Movimentações sem alterar o total de dívidas; a possível correspondência manual também aparecerá na Leitura Financeira.":"Possíveis duplicidades da fatura começam desmarcadas para não aumentar suas dívidas por engano."}</span></div>}
   <div className="reviewTableWrap"><table className={`reviewTable ${activeType==="credit_card"?"cardReviewTable":""}`}><thead><tr><th>Importar</th><th>Data e nome que será exibido</th><th>Pagamento</th><th>Categoria sugerida</th>{activeType==="credit_card"&&<th>Parcelas</th>}<th>Valor</th><th>Análise</th></tr></thead><tbody>{preview.items.map(item=>{const installment=installmentOverrides[item.fingerprint]||{current:null,total:null};return <tr key={item.fingerprint} className={item.duplicateKind?"duplicateRow":""}><td><input aria-label={`Importar ${item.description}`} type="checkbox" checked={selected.has(item.fingerprint)} disabled={item.duplicateKind==="already_imported"||item.duplicateKind==="within_file"} onChange={()=>toggle(item.fingerprint)}/></td><td title={item.rawDescription}><span>{new Date(item.date+"T12:00:00").toLocaleDateString("pt-BR")}</span><input className="merchantNameInput" aria-label={`Nome de ${item.description}`} maxLength={60} value={nameOverrides[item.fingerprint]??item.description} onChange={event=>setNameOverrides({...nameOverrides,[item.fingerprint]:event.target.value})}/><small className={`merchantNameHint ${item.nameLearned?"learned":""}`}>{item.nameLearned?"✓ Nome lembrado da sua última correção":"Toque para corrigir o nome"}</small></td><td><span className="paymentMethodTag">{item.paymentMethod}</span></td><td><select value={categoryOverrides[item.fingerprint]||item.category} onChange={event=>setCategoryOverrides({...categoryOverrides,[item.fingerprint]:event.target.value})}>{[...new Set([item.category,...categories])].map(category=><option key={category}>{category}</option>)}</select><small>Confiança {item.confidence==="high"?"alta":item.confidence==="medium"?"média":"baixa"}</small></td>{activeType==="credit_card"&&<td><div className="installmentReview"><input aria-label={`Parcela atual de ${item.description}`} type="number" min="1" placeholder="Atual" value={installment.current??""} onChange={event=>{const current=event.target.value?Number(event.target.value):null;setInstallmentOverrides({...installmentOverrides,[item.fingerprint]:{...installment,current}})}}/><span>de</span><input aria-label={`Total de parcelas de ${item.description}`} type="number" min="2" placeholder="Total" value={installment.total??""} onChange={event=>{const total=event.target.value?Number(event.target.value):null;setInstallmentOverrides({...installmentOverrides,[item.fingerprint]:{...installment,total}})}}/></div><small>{installment.current&&installment.total?`Parcela ${installment.current} de ${installment.total}`:"Compra à vista"}</small></td>}<td><strong>{BRL.format(item.amount)}</strong></td><td>{item.duplicateKind?<span className="duplicateTag">Revisar</span>:<span className="readyTag">Pronto</span>}<small>{item.duplicateReason||"Nenhuma correspondência encontrada."}</small></td></tr>})}</tbody></table></div>
   <div className="reviewFooter"><div><span>{selected.size} selecionadas</span><strong>{BRL.format(selectedTotal)}</strong></div><button disabled={busy} onClick={commit}>{busy?"Importando…":"Confirmar importação"}</button></div>
  </div>}
 </section>;
}
