"use client";
import {useEffect,useMemo,useState} from "react";
import StatementImport from "../components/StatementImport";

type Purchase={id:number|string;name:string;amount:number;type:string;period:string;category:string;transactionDate:string;installmentCurrent?:number|null;installmentTotal?:number|null;possibleDuplicateOf?:number|string|null;importInfo?:{accountName?:string;fileName?:string}};
type MonthOption={monthKey:string;duePeriods:number[]};
type Data={monthKey:string;months:MonthOption[];purchases:Purchase[];profile:{themeBg:string;themeAccent:string;themeSurface:string}};
const BRL=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const monthName=(key:string)=>new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${key}-01T00:00:00Z`)).replace(/^./,letter=>letter.toUpperCase());
const shortDate=(date:string)=>date?new Date(`${date}T12:00:00`).toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}):"Data não informada";

export default function CreditCards(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[showImport,setShowImport]=useState(true);
 const load=async(month?:string)=>{setLoading(true);setMessage("");try{const response=await fetch(`/api/cards${month?`?month=${month}`:""}`),result=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(result.error||"Não foi possível carregar as faturas.");setData(result);document.documentElement.style.setProperty("--user-bg",result.profile.themeBg);document.documentElement.style.setProperty("--user-accent",result.profile.themeAccent);document.documentElement.style.setProperty("--user-surface",result.profile.themeSurface)}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível carregar as faturas.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const total=useMemo(()=>data?.purchases.reduce((sum,item)=>sum+Number(item.amount||0),0)||0,[data]),installments=data?.purchases.filter(item=>item.installmentCurrent&&item.installmentTotal)||[],cards=useMemo(()=>{const grouped=new Map<string,Purchase[]>();for(const purchase of data?.purchases||[]){const name=purchase.importInfo?.accountName||"Cartão não informado";grouped.set(name,[...(grouped.get(name)||[]),purchase])}return [...grouped.entries()]},[data]),months=data?.months.map(item=>item.monthKey)||[],periods=Object.fromEntries(data?.months.map(item=>[item.monthKey,item.duePeriods])||[]);
 return <main className="cardsPage">
  <nav className="viewNav desktopViewNav" aria-label="Área do dashboard"><a href="/">Visão mensal</a><a href="/movimentacoes">Movimentações</a><a className="active" href="/cartao">Cartão de crédito</a><a href="/resumo">Resumo anual</a><a href="/dados">Dados e backup</a><a href="/leitura">Leitura</a><a href="/metas">Metas</a></nav>
  <header className="cardsHeader"><div><span className="eyebrow">COMPRAS QUE AINDA SERÃO PAGAS</span><h1>Cartão de crédito</h1><p>Importe sua fatura, confira cada compra e envie tudo corretamente para as dívidas da visão mensal.</p></div>{data&&<div className="cardHeaderActions"><select aria-label="Selecionar mês da fatura" value={data.monthKey} onChange={event=>load(event.target.value)}>{data.months.map(month=><option value={month.monthKey} key={month.monthKey}>{monthName(month.monthKey)}</option>)}</select><button className={showImport?"open":""} onClick={()=>setShowImport(value=>!value)}>{showImport?"Fechar importação":"+ Importar fatura"}</button></div>}</header>
  {showImport&&data&&<StatementImport mode="credit-card" months={months} initialMonth={data.monthKey} duePeriodsByMonth={periods} onImported={async()=>{await load(data.monthKey);setShowImport(false)}}/>}
  <section className="cardMetrics"><article className="featured"><span>Total das faturas</span><strong>{BRL.format(total)}</strong><small>{data?.purchases.length||0} compras enviadas para a visão mensal</small></article><article><span>Compras parceladas</span><strong>{installments.length}</strong><small>{BRL.format(installments.reduce((sum,item)=>sum+item.amount,0))} neste mês</small></article><article><span>Cartões identificados</span><strong>{cards.length}</strong><small>{cards.length===1?"Uma fatura importada":"Faturas separadas por cartão"}</small></article></section>
  {message&&<div className="movementMessage" role="status">{message}</div>}
  {loading?<div className="movementsEmpty">Carregando as compras do cartão…</div>:!data?.purchases.length?<section className="movementsEmpty"><b>Nenhuma fatura importada neste mês</b><p>Envie um arquivo OFX, CSV ou PDF para conferir data, nome, valor e parcelas antes de adicionar as compras às dívidas.</p><button onClick={()=>setShowImport(true)}>Importar fatura</button></section>:<section className="cardStatements">{cards.map(([card,purchases])=><article className="cardStatement" key={card}><div className="cardStatementHead"><div><span>FATURA IMPORTADA</span><h2>{card}</h2><small>{purchases[0]?.importInfo?.fileName||"Arquivo da fatura"}</small></div><div><span>Vence dia {purchases[0]?.period||"—"}</span><strong>{BRL.format(purchases.reduce((sum,item)=>sum+item.amount,0))}</strong></div></div><div className="cardPurchaseList">{purchases.map(item=><a className="cardPurchase" href={`/?month=${data.monthKey}`} key={item.id}><span className="purchaseDate">{shortDate(item.transactionDate)}</span><div><b>{item.name}</b><small>{item.category||"Categoria a conferir"}{item.installmentCurrent&&item.installmentTotal?` · Parcela ${item.installmentCurrent} de ${item.installmentTotal}`:" · Compra à vista"}</small></div>{item.possibleDuplicateOf&&<i>Revisar duplicidade</i>}<strong>{BRL.format(item.amount)}</strong><span className="purchaseArrow">→</span></a>)}</div></article>)}</section>}
  <p className="movementFootnote">Cada compra importada aparece também na visão mensal, no vencimento escolhido para a fatura.</p>
  <nav className="mobileViewNav sevenItemNav cardsMobileNav" aria-label="Área do dashboard"><a href="/"><span>▤</span>Mês</a><a href="/movimentacoes"><span>↕</span>Mov.</a><a className="active" href="/cartao"><span>▣</span>Cartão</a><a href="/resumo"><span>▥</span>Ano</a><a href="/dados"><span>↓</span>Dados</a><a href="/leitura"><span>◆</span>Leitura</a><a href="/metas"><span>◎</span>Metas</a></nav>
 </main>;
}
