"use client";
import {useEffect,useMemo,useState} from "react";

type Expense={id:number;name:string;amount:number;type:string;owner:string;note:string;confirmed:boolean;period:string;paymentStatus?:"pending"|"paid";paidDate?:string;installmentCurrent?:number|null;installmentTotal?:number|null};
type FreelanceJob={id:number;name:string;amount:number;owner:string;note:string};
type Month={monthKey:string;income:number;incomeRobson:number|null;incomeGabi:number|null;freelancers:FreelanceJob[];foodRobson:number;foodGabi:number;expenses:Expense[]};
type Backup={profile:{themeBg:string;themeAccent:string;themeSurface:string;financeMode?:"individual"|"family";primaryPersonName?:string;secondaryPersonName?:string};months:Month[]};
type Insight={id:string;tone:"positive"|"attention"|"important"|"neutral";title:string;summary:string;evidence:string;action:string};

const BRL=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const money=(value:number)=>BRL.format(value);
const monthName=(key:string)=>{const [year,month]=key.split("-").map(Number);return new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(year,month-1,1))).replace(/^./,c=>c.toUpperCase())};
const shiftMonth=(key:string,amount:number)=>{const [year,month]=key.split("-").map(Number),date=new Date(Date.UTC(year,month-1+amount,1));return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,"0")}`};
const fixedIncome=(month:Month)=>Number(month.incomeRobson??0)+Number(month.incomeGabi??0)||Number(month.income||0);
const freelanceIncome=(month:Month)=>month.freelancers.reduce((sum,item)=>sum+Number(item.amount||0),0);
const expenseTotal=(month:Month)=>month.expenses.reduce((sum,item)=>sum+Number(item.amount||0),0);
const foodExpense=(month:Month)=>month.expenses.filter(item=>/aliment|mercado|supermerc|ifood|refei|lanche|restaurante/i.test(item.name)).reduce((sum,item)=>sum+Number(item.amount||0),0);

function buildInsights(months:Month[],currentKey:string):Insight[]{
 const ordered=[...months].sort((a,b)=>a.monthKey.localeCompare(b.monthKey)),current=ordered.find(month=>month.monthKey===currentKey);
 if(!current)return [];
 const insights:Insight[]=[],fixed=fixedIncome(current),freelance=freelanceIncome(current),expenses=expenseTotal(current);
 const installments=current.expenses.filter(item=>item.type==="Parcela"),installmentValue=installments.reduce((sum,item)=>sum+Number(item.amount||0),0);
 if(installmentValue>0&&fixed>0){const percent=installmentValue/fixed*100;insights.push({id:"installments",tone:percent>=25?"important":percent>=15?"attention":"neutral",title:`Parcelas consomem ${percent.toFixed(1).replace(".",",")}% da renda fixa`,summary:`São ${money(installmentValue)} mensais em ${installments.length} ${installments.length===1?"parcela ativa":"parcelas ativas"}.`,evidence:`${money(installmentValue)} em parcelas ÷ ${money(fixed)} de renda fixa = ${percent.toFixed(1).replace(".",",")}%. Consideramos somente lançamentos marcados como “Parcela”.`,action:percent>=20?"Evite assumir novas parcelas até que parte desse valor seja liberada.":"Acompanhe as datas de término antes de assumir novos compromissos."})}
 const recent=ordered.filter(month=>month.monthKey<=currentKey).slice(-3),dependent=recent.filter(month=>{const base=fixedIncome(month),extra=freelanceIncome(month),cost=expenseTotal(month);return extra>0&&cost>base&&cost<=base+extra});
 if(recent.length>=2&&dependent.length)insights.push({id:"freelance",tone:dependent.length>=2?"important":"attention",title:`Freelancers fecharam ${dependent.length} dos últimos ${recent.length} meses`,summary:"Nesses meses, a renda fixa sozinha não cobriu todos os gastos cadastrados.",evidence:dependent.map(month=>`${monthName(month.monthKey)}: ${money(expenseTotal(month))} em gastos, ${money(fixedIncome(month))} de renda fixa e ${money(freelanceIncome(month))} de freelancers`).join(" • "),action:"Use a renda fixa como limite para gastos recorrentes e trate freelancers como margem ou reserva."});
 const subscriptions=current.expenses.filter(item=>/spotify|netflix|prime|disney|hbo|max|youtube|icloud|google one|deezer|amazon|assinatura/i.test(item.name)),subscriptionValue=subscriptions.reduce((sum,item)=>sum+Number(item.amount||0),0);
 if(subscriptions.length)insights.push({id:"subscriptions",tone:subscriptionValue*12>=1000?"attention":"neutral",title:`${subscriptions.length} ${subscriptions.length===1?"assinatura representa":"assinaturas representam"} ${money(subscriptionValue*12)} por ano`,summary:`O custo mensal identificado é de ${money(subscriptionValue)}.`,evidence:`${subscriptions.map(item=>`${item.name}: ${money(Number(item.amount||0))}`).join(" + ")}. Total mensal × 12 = ${money(subscriptionValue*12)}.`,action:"Revise se todos os serviços continuam sendo utilizados e se existem planos duplicados."});
 const unconfirmed=current.expenses.filter(item=>!item.confirmed),unconfirmedValue=unconfirmed.reduce((sum,item)=>sum+Number(item.amount||0),0);
 if(unconfirmedValue>0)insights.push({id:"unconfirmed",tone:"attention",title:`Existem ${money(unconfirmedValue)} ainda não confirmados`,summary:`${unconfirmed.length} ${unconfirmed.length===1?"lançamento pode":"lançamentos podem"} alterar o saldo real do mês.`,evidence:unconfirmed.map(item=>`${item.name}: ${money(Number(item.amount||0))}`).join(" • "),action:"Confirme esses valores antes de tomar decisões com base no saldo disponível."});
 const ending=installments.filter(item=>item.installmentCurrent&&item.installmentTotal&&item.installmentTotal>item.installmentCurrent).map(item=>({...item,remaining:Number(item.installmentTotal)-Number(item.installmentCurrent)})).filter(item=>item.remaining<=6);
 if(ending.length){const soonest=Math.min(...ending.map(item=>item.remaining)),items=ending.filter(item=>item.remaining===soonest),released=items.reduce((sum,item)=>sum+Number(item.amount||0),0),endKey=shiftMonth(currentKey,soonest);insights.push({id:"ending",tone:"positive",title:`Em ${monthName(endKey)}, ${items.length} ${items.length===1?"parcela termina":"parcelas terminam"} e liberam ${money(released)}`,summary:"Esse valor deixará de comprometer o orçamento se não for substituído por uma nova parcela.",evidence:items.map(item=>`${item.name}: parcela ${item.installmentCurrent}/${item.installmentTotal}, ${money(Number(item.amount||0))} por mês`).join(" • "),action:"Planeje agora o destino do valor liberado: reserva, antecipação de dívida ou meta."})}
 const foodMonths=recent.map(month=>({key:month.monthKey,value:foodExpense(month)})).filter(item=>item.value>0);
 if(foodMonths.length===3&&foodMonths[0].value<foodMonths[1].value&&foodMonths[1].value<foodMonths[2].value){const growth=(foodMonths[2].value/foodMonths[0].value-1)*100;insights.push({id:"food",tone:"attention",title:"Alimentação aumentou por três meses consecutivos",summary:`A alta acumulada foi de ${growth.toFixed(1).replace(".",",")}%, chegando a ${money(foodMonths[2].value)}.`,evidence:foodMonths.map(item=>`${monthName(item.key)}: ${money(item.value)}`).join(" → "),action:"Compare os lançamentos para identificar se a alta veio de mercado, refeições ou compras pontuais."})}
 const balance=fixed+freelance-expenses;
 if(insights.length<3)insights.push({id:"balance",tone:balance>=0?"positive":"important",title:balance>=0?`O mês mantém saldo de ${money(balance)}`:`O mês está negativo em ${money(Math.abs(balance))}`,summary:balance>=0?"As entradas cadastradas cobrem os gastos atuais.":"Os gastos cadastrados superam as entradas do mês.",evidence:`${money(fixed)} de renda fixa + ${money(freelance)} de freelancers − ${money(expenses)} em gastos = ${money(balance)}.`,action:balance>=0?"Defina antecipadamente quanto desse saldo será reservado.":"Revise primeiro valores não confirmados e gastos que podem ser adiados."});
 return insights.slice(0,6);
}

export default function FinancialReading(){
 const [backup,setBackup]=useState<Backup|null>(null),[monthKey,setMonthKey]=useState(""),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/backup").then(response=>{if(!response.ok)throw new Error();return response.json()}).then((data:Backup)=>{setBackup(data);const latest=data.months.at(-1)?.monthKey||"";setMonthKey(latest);document.documentElement.style.setProperty("--user-bg",data.profile.themeBg);document.documentElement.style.setProperty("--user-accent",data.profile.themeAccent);document.documentElement.style.setProperty("--user-surface",data.profile.themeSurface)}).catch(()=>setError("Não foi possível carregar sua leitura financeira."))},[]);
 const insights=useMemo(()=>{if(!backup||!monthKey)return [];const mode=backup.profile.financeMode||"individual",months=backup.months.map(month=>mode==="individual"?{...month,income:Number(month.incomeRobson??month.income??0),incomeGabi:null}:month);return buildInsights(months,monthKey)},[backup,monthKey]);
 return <main className="intelligencePage">
  <nav className="viewNav desktopViewNav" aria-label="Área do dashboard"><a href="/">Visão mensal</a><a href="/resumo">Resumo anual</a><a href="/dados">Dados e backup</a><a className="active" href="/leitura">Leitura</a><a href="/metas">Metas</a></nav>
  <section className="financialIntelligence standalone"><div className="intelligenceHead"><div><span className="eyebrow">LEITURA FINANCEIRA</span><h1>O que seus números mostram</h1><p>Conclusões calculadas com seus lançamentos reais e o histórico disponível.</p></div><div className="intelligenceControls">{backup&&<select aria-label="Mês analisado" value={monthKey} onChange={event=>setMonthKey(event.target.value)}>{backup.months.map(month=><option key={month.monthKey} value={month.monthKey}>{monthName(month.monthKey)}</option>)}</select>}<span className="analysisBadge"><i/> Análise atualizada</span></div></div>
  {error?<div className="intelligenceEmpty">{error}</div>:!backup?<div className="intelligenceEmpty">Analisando seus dados…</div>:<div className="insightGrid">{insights.map((insight,index)=><article className={`insightCard ${insight.tone}`} key={insight.id}><div className="insightTop"><span>{String(index+1).padStart(2,"0")}</span><i>{insight.tone==="positive"?"Positivo":insight.tone==="important"?"Importante":insight.tone==="attention"?"Atenção":"Informativo"}</i></div><h3>{insight.title}</h3><p>{insight.summary}</p><details><summary>Como chegamos nisso</summary><div className="insightEvidence">{insight.evidence}</div></details><div className="insightAction"><b>Próximo passo</b><span>{insight.action}</span></div></article>)}</div>}
  <p className="analysisFootnote">A análise utiliza cálculos do sistema. Ela não altera seus dados nem movimenta dinheiro.</p></section>
  <nav className="mobileViewNav" aria-label="Área do dashboard"><a href="/"><span>▤</span>Mês</a><a href="/resumo"><span>▥</span>Ano</a><a href="/dados"><span>↓</span>Dados</a><a className="active" href="/leitura"><span>◆</span>Leitura</a><a href="/metas"><span>◎</span>Metas</a></nav>
 </main>
}