export type DocumentType="bank_statement"|"credit_card";
export type ExistingExpense={id:number|string;name?:string;amount?:number;period?:string;importInfo?:{fingerprint?:string};reconciliationIssues?:ReconciliationIssue[]};
export type ReconciliationIssue={fingerprint:string;date:string;description:string;amount:number;category:string;accountName:string;fileName:string;detectedAt:string;status:"pending"};
export type ImportedTransaction={fingerprint:string;sourceId:string;date:string;description:string;amount:number;direction:"expense"|"income";category:string;confidence:"high"|"medium"|"low";duplicateKind:"already_imported"|"possible_manual"|"within_file"|null;matchedExpenseId:number|string|null;matchedExpenseName:string|null;duplicateReason:string|null};

const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(pagamento|compra|debito|credito|pix|transf|transferencia|recebido|enviado|cartao|visa|mastercard|elo)\b/g," ").replace(/[^a-z0-9]+/g," ").trim();
const fingerprint=(value:string)=>{let hash=2166136261;for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return `txn_${(hash>>>0).toString(36)}`};
const parseMoney=(raw:string)=>{const clean=raw.replace(/R\$|\s/g,"").replace(/[^\d,.-]/g,"");if(!clean)return 0;const comma=clean.lastIndexOf(","),dot=clean.lastIndexOf(".");const normalized=comma>dot?clean.replace(/\./g,"").replace(",","."):clean.replace(/,/g,"");return Number(normalized)||0};
const parseDate=(raw:string)=>{const value=raw.trim();let match=value.match(/^(\d{4})[-/]?(\d{2})[-/]?(\d{2})/);if(match)return `${match[1]}-${match[2]}-${match[3]}`;match=value.match(/^(\d{2})[\/.\-](\d{2})[\/.\-](\d{2,4})/);if(match){const year=match[3].length===2?`20${match[3]}`:match[3];return `${year}-${match[2]}-${match[1]}`}return ""};
const tag=(block:string,name:string)=>block.match(new RegExp(`<${name}>\\s*([^<\\r\\n]+)`,"i"))?.[1]?.trim()||"";

function parseOfx(content:string){return [...content.matchAll(/<STMTTRN>([\s\S]*?)(?=<STMTTRN>|<\/BANKTRANLIST>|<\/STMTTRN>)/gi)].map(match=>{const block=match[1],amount=parseMoney(tag(block,"TRNAMT")),date=parseDate(tag(block,"DTPOSTED")),sourceId=tag(block,"FITID"),description=tag(block,"NAME")||tag(block,"MEMO")||"Movimentação bancária";return {sourceId,date,description,amount:Math.abs(amount),direction:amount<0?"expense" as const:"income" as const}}).filter(item=>item.date&&item.amount>0)}

function splitCsvLine(line:string,delimiter:string){const cells:string[]=[];let current="",quoted=false;for(let index=0;index<line.length;index++){const character=line[index];if(character==='"'&&line[index+1]==='"'&&quoted){current+='"';index++}else if(character==='"')quoted=!quoted;else if(character===delimiter&&!quoted){cells.push(current.trim());current=""}else current+=character}cells.push(current.trim());return cells}
const headerKey=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
function parseCsv(content:string){const lines=content.replace(/^\uFEFF/,"").split(/\r?\n/).filter(line=>line.trim());if(lines.length<2)return [];const delimiter=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?";":",";const headers=splitCsvLine(lines[0],delimiter).map(headerKey);const find=(names:string[])=>headers.findIndex(header=>names.some(name=>header===name||header.startsWith(name)));const dateIndex=find(["data","datamovimento","datatransacao","date"]),descriptionIndex=find(["descricao","historico","estabelecimento","lancamento","detalhes","description","memo"]),amountIndex=find(["valor","valortransacao","amount"]),debitIndex=find(["debito","saida","valordebito"]),creditIndex=find(["credito","entrada"]),idIndex=find(["id","identificador","fitid","documento"]);if(dateIndex<0||descriptionIndex<0||(amountIndex<0&&debitIndex<0&&creditIndex<0))return [];return lines.slice(1).map(line=>{const cells=splitCsvLine(line,delimiter),debit=debitIndex>=0?parseMoney(cells[debitIndex]||""):0,credit=creditIndex>=0?parseMoney(cells[creditIndex]||""):0,raw=amountIndex>=0?parseMoney(cells[amountIndex]||""):credit-debit;return {sourceId:idIndex>=0?cells[idIndex]||"":"",date:parseDate(cells[dateIndex]||""),description:(cells[descriptionIndex]||"Movimentação bancária").trim(),amount:Math.abs(raw),direction:(debit>0||raw<0?"expense":"income") as "expense"|"income"}}).filter(item=>item.date&&item.amount>0)}

const categoryRules:[RegExp,string][]=[[/ifood|restaurante|lanch|padaria|mercado|supermerc|hortifruti|acougue|refeicao/i,"Alimentação"],[/uber|99app|taxi|combust|posto |shell|ipiranga|estacion|pedagio/i,"Transporte"],[/netflix|spotify|disney|hbo|amazon prime|youtube|deezer|icloud|google one/i,"Assinaturas"],[/farmacia|drogaria|hospital|clinica|laborat|consulta/i,"Saúde"],[/energia|enel|light|agua|cedae|internet|telefone|vivo|claro|tim /i,"Contas da casa"],[/aluguel|condominio|imobiliaria/i,"Moradia"],[/escola|faculdade|curso|livraria/i,"Educação"],[/seguro|financiamento|emprestimo/i,"Dívidas e contratos"],[/salario|provento|pagamento empresa/i,"Renda fixa"],[/freela|cliente|servico prestado/i,"Freelancer"],[/estorno|reembolso/i,"Estorno ou reembolso"],[/pix|transferencia|ted|doc /i,"Transferência"]];
function classify(description:string,direction:"expense"|"income"){for(const [rule,category] of categoryRules)if(rule.test(description))return {category,confidence:"high" as const};return direction==="income"?{category:"Entrada a conferir",confidence:"low" as const}:{category:"Outros gastos",confidence:"low" as const}}
function similarity(left:string,right:string){const a=new Set(normalize(left).split(" ").filter(token=>token.length>2)),b=new Set(normalize(right).split(" ").filter(token=>token.length>2));if(!a.size||!b.size)return 0;let common=0;a.forEach(token=>{if(b.has(token))common++});return common/Math.max(a.size,b.size)}

export function parseStatement(content:string,fileName:string,existing:ExistingExpense[]):{items:ImportedTransaction[];ignoredIncome:number}{
 const raw=/<OFX>|<STMTTRN>/i.test(content)?parseOfx(content):parseCsv(content),seen=new Set<string>(),items:ImportedTransaction[]=[];let ignoredIncome=0;
 for(const transaction of raw){const classified=classify(transaction.description,transaction.direction),key=transaction.sourceId||`${transaction.date}|${transaction.amount.toFixed(2)}|${normalize(transaction.description)}`,id=fingerprint(key),sameFile=seen.has(id);seen.add(id);let duplicateKind:ImportedTransaction["duplicateKind"]=sameFile?"within_file":null,matched:ExistingExpense|undefined,reason=sameFile?"A mesma movimentação aparece mais de uma vez no arquivo.":null;
  if(transaction.direction==="income")ignoredIncome++;
  if(!sameFile){matched=existing.find(expense=>expense.importInfo?.fingerprint===id);if(matched){duplicateKind="already_imported";reason="Esta movimentação já foi importada anteriormente."}else{matched=existing.find(expense=>Math.abs(Number(expense.amount||0)-transaction.amount)<.01&&similarity(expense.name||"",transaction.description)>=.34);if(matched){duplicateKind="possible_manual";reason=`Mesmo valor e descrição semelhante a “${matched.name||"lançamento manual"}”.`}}}
  items.push({...transaction,fingerprint:id,category:classified.category,confidence:classified.confidence,duplicateKind,matchedExpenseId:matched?.id??null,matchedExpenseName:matched?.name||null,duplicateReason:reason});
 }
 return {items,ignoredIncome};
}

export function duePeriodFor(date:string,duePeriods:number[]){const day=Number(date.slice(8,10)),ordered=[...duePeriods].sort((a,b)=>a-b);return String(ordered.find(period=>period>=day)??ordered.at(-1)??10)}
