export type DocumentType="bank_statement"|"credit_card";
export type ExistingExpense={id:number|string;name?:string;rawDescription?:string;amount?:number;period?:string;recordKind?:"expense"|"bank_movement";merchantKey?:string;userEditedName?:boolean;importInfo?:{fingerprint?:string;documentType?:DocumentType};reconciliationIssues?:ReconciliationIssue[]};
export type ReconciliationIssue={fingerprint:string;date:string;description:string;amount:number;category:string;accountName:string;fileName:string;detectedAt:string;status:"pending"};
export type ImportedTransaction={fingerprint:string;sourceId:string;date:string;description:string;rawDescription:string;merchantKey:string;nameLearned:boolean;paymentMethod:string;amount:number;direction:"expense"|"income";category:string;confidence:"high"|"medium"|"low";installmentCurrent:number|null;installmentTotal:number|null;duplicateKind:"already_imported"|"possible_manual"|"within_file"|null;matchedExpenseId:number|string|null;matchedExpenseName:string|null;duplicateReason:string|null};

const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(pagamento|compra|debito|credito|pix|transf|transferencia|recebida|recebido|enviada|enviado|para|pelo|pela|cartao|visa|mastercard|elo)\b/g," ").replace(/[^a-z0-9]+/g," ").trim();
const fingerprint=(value:string)=>{let hash=2166136261;for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return `txn_${(hash>>>0).toString(36)}`};
const parseMoney=(raw:string)=>{const clean=raw.replace(/R\$|\s/g,"").replace(/[^\d,.-]/g,"");if(!clean)return 0;const comma=clean.lastIndexOf(","),dot=clean.lastIndexOf(".");const normalized=comma>dot?clean.replace(/\./g,"").replace(",","."):clean.replace(/,/g,"");return Number(normalized)||0};
const monthNumbers:Record<string,string>={jan:"01",janeiro:"01",fev:"02",fevereiro:"02",mar:"03",marco:"03",março:"03",abr:"04",abril:"04",mai:"05",maio:"05",jun:"06",junho:"06",jul:"07",julho:"07",ago:"08",agosto:"08",set:"09",setembro:"09",out:"10",outubro:"10",nov:"11",novembro:"11",dez:"12",dezembro:"12"};
const parseDate=(raw:string,fallbackMonth="")=>{const value=raw.trim();let match=value.match(/^(\d{4})[-/]?(\d{2})[-/]?(\d{2})/);if(match)return `${match[1]}-${match[2]}-${match[3]}`;match=value.match(/^(\d{1,2})[\/.\-](\d{1,2})(?:[\/.\-](\d{2,4}))?/);if(match){const year=match[3]?(match[3].length===2?`20${match[3]}`:match[3]):fallbackMonth.slice(0,4);return year?`${year}-${match[2].padStart(2,"0")}-${match[1].padStart(2,"0")}`:""}match=value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().match(/^(\d{1,2})\s+([a-z]+)(?:\s+(\d{2,4}))?/);if(match){const month=monthNumbers[match[2]],year=match[3]?(match[3].length===2?`20${match[3]}`:match[3]):fallbackMonth.slice(0,4);return month&&year?`${year}-${month}-${match[1].padStart(2,"0")}`:""}return ""};
const tag=(block:string,name:string)=>block.match(new RegExp(`<${name}>\\s*([^<\\r\\n]+)`,"i"))?.[1]?.trim()||"";

function parseOfx(content:string){return [...content.matchAll(/<STMTTRN>([\s\S]*?)(?=<STMTTRN>|<\/BANKTRANLIST>|<\/STMTTRN>)/gi)].map(match=>{const block=match[1],amount=parseMoney(tag(block,"TRNAMT")),date=parseDate(tag(block,"DTPOSTED")),sourceId=tag(block,"FITID"),name=tag(block,"NAME"),memo=tag(block,"MEMO"),description=[name,memo&&normalize(memo)!==normalize(name)?memo:""].filter(Boolean).join(" • ")||"Movimentação bancária";return {sourceId,date,description,amount:Math.abs(amount),direction:amount<0?"expense" as const:"income" as const}}).filter(item=>item.date&&item.amount>0)}

function splitCsvLine(line:string,delimiter:string){const cells:string[]=[];let current="",quoted=false;for(let index=0;index<line.length;index++){const character=line[index];if(character==='"'&&line[index+1]==='"'&&quoted){current+='"';index++}else if(character==='"')quoted=!quoted;else if(character===delimiter&&!quoted){cells.push(current.trim());current=""}else current+=character}cells.push(current.trim());return cells}
const headerKey=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
function parseCsv(content:string){const lines=content.replace(/^\uFEFF/,"").split(/\r?\n/).filter(line=>line.trim());if(lines.length<2)return [];const delimiter=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?";":",";const headers=splitCsvLine(lines[0],delimiter).map(headerKey);const find=(names:string[])=>headers.findIndex(header=>names.some(name=>header===name||header.startsWith(name)));const dateIndex=find(["data","datamovimento","datatransacao","date"]),descriptionIndex=find(["descricao","historico","estabelecimento","lancamento","detalhes","description","memo"]),amountIndex=find(["valor","valortransacao","amount"]),debitIndex=find(["debito","saida","valordebito"]),creditIndex=find(["credito","entrada"]),idIndex=find(["id","identificador","fitid","documento"]);if(dateIndex<0||descriptionIndex<0||(amountIndex<0&&debitIndex<0&&creditIndex<0))return [];return lines.slice(1).map(line=>{const cells=splitCsvLine(line,delimiter),debit=debitIndex>=0?parseMoney(cells[debitIndex]||""):0,credit=creditIndex>=0?parseMoney(cells[creditIndex]||""):0,raw=amountIndex>=0?parseMoney(cells[amountIndex]||""):credit-debit;return {sourceId:idIndex>=0?cells[idIndex]||"":"",date:parseDate(cells[dateIndex]||""),description:(cells[descriptionIndex]||"Movimentação bancária").trim(),amount:Math.abs(raw),direction:(debit>0||raw<0?"expense":"income") as "expense"|"income"}}).filter(item=>item.date&&item.amount>0)}

const pdfDatePattern=/\b(\d{1,2}[\/.\-]\d{1,2}(?:[\/.\-]\d{2,4})?|\d{1,2}\s+(?:jan(?:eiro)?|fev(?:ereiro)?|mar(?:ço|co)?|abr(?:il)?|mai(?:o)?|jun(?:ho)?|jul(?:ho)?|ago(?:sto)?|set(?:embro)?|out(?:ubro)?|nov(?:embro)?|dez(?:embro)?)(?:\s+\d{2,4})?)\b/i;
const pdfMoneyPattern=/(?:^|\s)([-−]?\s*(?:R\$\s*)?(?:\d{1,3}(?:\.\d{3})+|\d+),\d{2}\s*[DC]?)(?=\s|$)/gi;
function parsePdfText(content:string,fallbackMonth:string){
 const lines=content.split(/\r?\n/).map(line=>line.replace(/\s+/g," ").trim()).filter(Boolean),items:{sourceId:string;date:string;description:string;amount:number;direction:"expense"|"income"}[]=[];let currentDate="",buffer:string[]=[];
 for(const line of lines){
  const dateText=line.match(pdfDatePattern)?.[1];if(dateText){currentDate=parseDate(dateText,fallbackMonth);buffer=[]}if(!currentDate)continue;
  const withoutDate=line.replace(pdfDatePattern," ").trim();if(/saldo\s+(?:anterior|do\s+dia|dispon[ií]vel|atual)/i.test(withoutDate)){buffer=[];continue}if(withoutDate)buffer.push(withoutDate);if(buffer.length>8)buffer=buffer.slice(-8);
  const candidates=[...withoutDate.matchAll(pdfMoneyPattern)].map(match=>match[1]);if(!candidates.length)continue;
  const selected=candidates.find(value=>/^\s*[-−]/.test(value)||/D\s*$/i.test(value))||candidates[0],blockText=buffer.join(" "),explicitIncome=/\b(?:recebid[oa]|entrada|dep[oó]sito|estorno|reembolso|cr[eé]dito recebido)\b/i.test(blockText),expense=!explicitIncome&&(/^\s*[-−]/.test(selected)||/D\s*$/i.test(selected)||/\b(?:enviad[oa]|compra|pagamento|pgto|d[eé]bito|boleto|saque|tarifa|transfer[eê]ncia realizada)\b/i.test(blockText)),amount=Math.abs(parseMoney(selected.replace(/[DC]\s*$/i,"")));
  const description=buffer.map(value=>value.replace(pdfMoneyPattern," ").replace(/\b(?:data|descri[cç][aã]o|hist[oó]rico|valor)\b/gi," ").trim()).filter(value=>value.length>1).join(" • ").replace(/\s+/g," ").trim()||"Movimentação bancária";buffer=[];if(!amount||/^(?:saldo|total|extrato|per[ií]odo)\b/i.test(description))continue;items.push({sourceId:"",date:currentDate,description,amount,direction:expense?"expense":"income"});
 }
 return items;
}

const categoryRules:[RegExp,string][]=[[/ifood|restaurante|lanch|padaria|mercado|supermerc|hortifruti|acougue|refeicao/i,"Alimentação"],[/uber|99app|taxi|combust|posto |shell|ipiranga|estacion|pedagio/i,"Transporte"],[/netflix|spotify|disney|hbo|amazon prime|youtube|deezer|icloud|google one/i,"Assinaturas"],[/farmacia|drogaria|hospital|clinica|laborat|consulta/i,"Saúde"],[/energia|enel|light|agua|cedae|internet|telefone|vivo|claro|tim /i,"Contas da casa"],[/aluguel|condominio|imobiliaria/i,"Moradia"],[/escola|faculdade|curso|livraria/i,"Educação"],[/seguro|financiamento|emprestimo/i,"Dívidas e contratos"],[/salario|provento|pagamento empresa/i,"Renda fixa"],[/freela|cliente|servico prestado/i,"Freelancer"],[/estorno|reembolso/i,"Estorno ou reembolso"],[/pix|transferencia|ted|doc /i,"Transferência"]];
function classify(description:string,direction:"expense"|"income"){for(const [rule,category] of categoryRules)if(rule.test(description))return {category,confidence:"high" as const};return direction==="income"?{category:"Entrada a conferir",confidence:"low" as const}:{category:"Outros gastos",confidence:"low" as const}}
function similarity(left:string,right:string){const a=new Set(normalize(left).split(" ").filter(token=>token.length>2)),b=new Set(normalize(right).split(" ").filter(token=>token.length>2));if(!a.size||!b.size)return 0;let common=0;a.forEach(token=>{if(b.has(token))common++});return common/Math.max(a.size,b.size)}

export function detectPaymentMethod(raw:string,documentType:DocumentType){if(/\bpix\b/i.test(raw))return "Pix";if(/d[eé]bito\s*autom[aá]tico|deb\.?\s*aut/i.test(raw))return "Débito automático";if(/cart[aã]o.{0,15}d[eé]bito|compra\s+d[eé]bito|d[eé]bito\s+cart[aã]o/i.test(raw))return "Cartão de débito";if(/cart[aã]o.{0,15}cr[eé]dito|compra\s+cr[eé]dito/i.test(raw)||documentType==="credit_card")return "Cartão de crédito";if(/boleto|c[oó]digo\s+de\s+barras/i.test(raw))return "Boleto";if(/\bted\b|\bdoc\b|transfer[eê]ncia|transf\.?/i.test(raw))return "Transferência";if(/saque/i.test(raw))return "Saque";if(/tarifa|encargo|juros|iof/i.test(raw))return "Tarifa bancária";return "Débito em conta"}
const friendlyBrands:Record<string,string>={ifood:"iFood",picpay:"PicPay",youtube:"YouTube",whatsapp:"WhatsApp",mcdonalds:"McDonald's",nubank:"Nubank",uber:"Uber",netflix:"Netflix",spotify:"Spotify",amazon:"Amazon",shopee:"Shopee",google:"Google",apple:"Apple",atacadao:"Atacadão"};
const friendlyCase=(value:string)=>value.split(/\s+/).filter(Boolean).map((word,index)=>{const key=normalize(word);if(friendlyBrands[key])return friendlyBrands[key];if(index>0&&/^(de|da|do|das|dos|e|em)$/.test(key))return key;return word.charAt(0).toLocaleUpperCase("pt-BR")+word.slice(1).toLocaleLowerCase("pt-BR")}).join(" ");
const unidentified="Identificação não informada pelo banco";
const meaningfulParty=(value:string)=>normalize(value)!==normalize(unidentified)&&!/^(?:no|na|pelo|pela|para|por|via|outros?)$/i.test(value.trim());
const installmentInfo=(raw:string)=>{const explicit=raw.match(/\b(?:parc(?:ela)?\.?\s*)?(\d{1,2})\s*(?:\/|de)\s*(\d{1,2})\b/i);if(!explicit)return {installmentCurrent:null,installmentTotal:null};const current=Number(explicit[1]),total=Number(explicit[2]);return current>=1&&total>=2&&current<=total?{installmentCurrent:current,installmentTotal:total}:{installmentCurrent:null,installmentTotal:null}};
export function cleanMerchantName(raw:string){let value=raw.replace(/[\r\n\t]+/g," ").replace(/\b(?:parc(?:ela)?\.?\s*)?\d{1,2}\s*(?:\/|de)\s*\d{1,2}\b/gi," ").replace(/\b(?:pay|qrs)\b/gi," ").replace(/\b(?:mercado\s*pago|mercadopago|pagseguro|stone|sumup|cielo|rede|pag)\s*\*\s*/gi," ").replace(/\b(?:transfer[eê]ncia\s+)?(?:enviad[oa]|recebid[oa])\s+(?:(?:pelo|pela|via)\s+)?(?:pix\s+)?(?:(?:para|de|do|da|a)\s+)?/gi," ").replace(/\b(?:cnpj|cpf)\s*[:.-]?\s*[\d.*\/-]+/gi," ").replace(/\s*[-•|]?\s*(?:\*{3}\.\d{3}\.\d{3}-\*{2}|\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}|\d{3}\.\d{3}\.\d{3}-\d{2}|(?:\*{3})?\.?\d{3}\.\d{3}(?:-\*{2})?|\d{1,3}(?:\.\d{3}){2,3})(?:\.{3})?\s*$/g," ").replace(/\s*[•|*]\s*/g," ").replace(/\b(?:aut(?:oriza[cç][aã]o)?|nsu|doc(?:umento)?|id|e2e)\s*[:#.-]?\s*[a-z0-9-]{5,}/gi," ").replace(/\*{2,}\d{2,}|\b(?:final|cart[aã]o)\s*\d{3,6}\b/gi," ").replace(/\d{1,2}[\/.-]\d{1,2}(?:[\/.-]\d{2,4})?\b|\b\d{2}:\d{2}(?::\d{2})?\b/g," ").replace(/\b(?:compra|pagamento|pgto|lan[cç]amento|d[eé]bito|cr[eé]dito|cart[aã]o|pix|enviada|enviado|recebida|recebido|realizada|realizado|transfer[eê]ncia|transf|ted|doc|boleto|online|presencial)\b/gi," ").replace(/\b(?:ltda|eireli|mei|s\/?a)\b\.?/gi," ").replace(/\b\d{7,}\b/g," ").replace(/[;|:_-]+/g," ").replace(/^\s*(?:para|pelo|pela|por)\s+/i," ").replace(/\s{2,}/g," ").trim();if(/\b(?:compra|cart[aã]o|d[eé]bito|cr[eé]dito)\b/i.test(raw))value=value.replace(/^(?:no|na)\s+/i,"");if(!value||value.length<2||/^(?:no|na|pelo|pela|para|por|via)$/i.test(value))value=unidentified;const words=value.split(" ").filter((word,index,list)=>!index||normalize(word)!==normalize(list[index-1])).slice(0,10);value=friendlyCase(words.join(" "));return value.length>64?`${value.slice(0,61).trim()}…`:value}
export function transactionDisplayName(raw:string,documentType:DocumentType,direction:"expense"|"income"="expense"){const party=cleanMerchantName(raw),method=detectPaymentMethod(raw,documentType),known=meaningfulParty(party);if(direction==="income")return known?`Recebido de ${party}`:"Entrada — identificação não informada";if(method==="Pix")return known?`Pix enviado para ${party}`:"Pix enviado — destinatário não informado";if(method==="Transferência")return known?`Transferência para ${party}`:"Transferência — destinatário não informado";if(method==="Cartão de débito")return known?party:"Compra no débito — estabelecimento não informado";if(method==="Cartão de crédito")return known?party:"Compra no crédito — estabelecimento não informado";if(method==="Débito automático")return known?party:"Débito automático — origem não informada";if(method==="Boleto")return known?party:"Pagamento de boleto — beneficiário não informado";if(method==="Saque")return "Saque em dinheiro";if(method==="Tarifa bancária")return known?party:"Tarifa bancária";return known?party:"Saída da conta — identificação não informada"}
export function merchantIdentity(raw:string){const party=cleanMerchantName(raw);return meaningfulParty(party)?normalize(party).split(" ").filter(token=>token.length>1).slice(0,4).join("-")||"nao-identificado":"nao-identificado"}

export function parseStatement(content:string,fileName:string,existing:ExistingExpense[],documentType:DocumentType="bank_statement",knownAliases:ExistingExpense[]=existing,fallbackMonth=""):{items:ImportedTransaction[];ignoredIncome:number}{
 const raw=/\.pdf$/i.test(fileName)?parsePdfText(content,fallbackMonth):/<OFX>|<STMTTRN>/i.test(content)?parseOfx(content):parseCsv(content),seen=new Set<string>(),items:ImportedTransaction[]=[];let ignoredIncome=0;
 for(const transaction of raw){const rawDescription=transaction.description,direction=documentType==="credit_card"&&!/estorno|reembolso|cr[eé]dito\s+recebido|pagamento\s+(?:da\s+)?fatura/i.test(rawDescription)?"expense":transaction.direction,merchantKey=merchantIdentity(rawDescription),learned=merchantKey==="nao-identificado"?undefined:knownAliases.find(expense=>(expense.merchantKey===merchantKey||Boolean(expense.rawDescription)&&merchantIdentity(expense.rawDescription||"")===merchantKey)&&expense.userEditedName&&expense.name?.trim()),description=learned?.name?.trim()||transactionDisplayName(rawDescription,documentType,direction),method=detectPaymentMethod(rawDescription,documentType),classified=classify(`${description} ${rawDescription}`,direction),installment=documentType==="credit_card"?installmentInfo(rawDescription):{installmentCurrent:null,installmentTotal:null},key=transaction.sourceId||`${transaction.date}|${transaction.amount.toFixed(2)}|${normalize(rawDescription)}`,id=fingerprint(key),sameFile=seen.has(id);seen.add(id);let duplicateKind:ImportedTransaction["duplicateKind"]=sameFile?"within_file":null,matched:ExistingExpense|undefined,reason=sameFile?"A mesma movimentação aparece mais de uma vez no arquivo.":null;
  if(direction==="income")ignoredIncome++;
  if(!sameFile){matched=knownAliases.find(expense=>expense.importInfo?.fingerprint===id);if(matched){duplicateKind="already_imported";reason="Esta movimentação já foi importada anteriormente."}else{matched=existing.find(expense=>expense.recordKind!=="bank_movement"&&Math.abs(Number(expense.amount||0)-transaction.amount)<.01&&similarity(expense.name||"",description)>=.34);if(matched){duplicateKind="possible_manual";reason=`Mesmo valor e estabelecimento semelhante a “${matched.name||"lançamento manual"}”.`}}}
  items.push({...transaction,direction,description,rawDescription,merchantKey,nameLearned:Boolean(learned),paymentMethod:method,fingerprint:id,category:classified.category,confidence:classified.confidence,...installment,duplicateKind,matchedExpenseId:matched?.id??null,matchedExpenseName:matched?.name||null,duplicateReason:reason});
 }
 return {items,ignoredIncome};
}

export function duePeriodFor(date:string,duePeriods:number[]){const day=Number(date.slice(8,10)),ordered=[...duePeriods].sort((a,b)=>a-b);return String(ordered.find(period=>period>=day)??ordered.at(-1)??10)}
