"use client";
import {ChangeEvent,useEffect,useMemo,useState} from "react";
import {buildExcel} from "./exportExcel";
import {buildMonthlyPdf} from "./exportPdf";

type Expense={name?:string;amount?:number;period?:string;owner?:string;type?:string;paymentStatus?:string;paidDate?:string;installmentCurrent?:number;installmentTotal?:number;note?:string};
type Job={name?:string;amount?:number;owner?:string;note?:string};
type Month={monthKey:string;income:number;expenses:Expense[];freelancers:Job[]};
type Backup={createdAt:string;profile:{themeBg:string;themeAccent:string;themeSurface:string};months:Month[]};
type ImportItem={fingerprint:string;date:string;description:string;amount:number;category:string;confidence:"high"|"medium"|"low";duplicateKind:"already_imported"|"possible_manual"|"within_file"|null;matchedExpenseName:string|null;duplicateReason:string|null};
type ImportPreview={items:ImportItem[];ignoredIncome:number;summary:{transactions:number;duplicates:number;ready:number}};

const fonts:Record<string,string>={modern:'Inter,"Segoe UI",system-ui,sans-serif',geometric:'"Avenir Next","Trebuchet MS","Segoe UI",sans-serif',rounded:'ui-rounded,"Arial Rounded MT Bold","Trebuchet MS",sans-serif'};
const categories=["Alimentação","Transporte","Assinaturas","Saúde","Contas da casa","Moradia","Educação","Dívidas e contratos","Transferência","Outros gastos"];
const BRL=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const monthName=(key:string)=>new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${key}-01T00:00:00Z`)).replace(/^./,character=>character.toUpperCase());
const saveBackup=async()=>{const response=await fetch("/api/backup");if(!response.ok)throw new Error();const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=response.headers.get("content-disposition")?.match(/filename="([^"]+)"/)?.[1]||"dashfinance-backup.json";link.click();URL.revokeObjectURL(url)};

export default function DataAndBackup(){
 const [info,setInfo]=useState<Backup|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[file,setFile]=useState<File|null>(null),[pdfMonth,setPdfMonth]=useState("");
 const [bankFile,setBankFile]=useState<File|null>(null),[documentType,setDocumentType]=useState<"bank_statement"|"credit_card">("bank_statement"),[accountName,setAccountName]=useState(""),[targetMonth,setTargetMonth]=useState(""),[preview,setPreview]=useState<ImportPreview|null>(null),[selected,setSelected]=useState<Set<string>>(new Set()),[categoryOverrides,setCategoryOverrides]=useState<Record<string,string>>({}),[importContent,setImportContent]=useState("");
 useEffect(()=>{fetch("/api/backup").then(response=>response.json()).then((backup:Backup)=>{setInfo(backup);const latest=backup.months.at(-1)?.monthKey||"";setPdfMonth(latest);setTargetMonth(latest);document.documentElement.style.setProperty("--user-bg",backup.profile.themeBg);document.documentElement.style.setProperty("--user-accent",backup.profile.themeAccent);document.documentElement.style.setProperty("--user-surface",backup.profile.themeSurface);document.documentElement.style.setProperty("--user-display-font",fonts[localStorage.getItem("dashfinance-font")||"modern"]||fonts.modern)}).catch(()=>setMessage("Não foi possível consultar seus dados agora."))},[]);
 const download=async(kind:"excel"|"pdf")=>{if(!info)return;setBusy(true);setMessage("");try{if(kind==="excel")await buildExcel(info);else{const month=info.months.find(item=>item.monthKey===pdfMonth);if(!month)throw new Error();await buildMonthlyPdf(month,info.profile)}setMessage(kind==="excel"?"Planilha Excel organizada baixada.":"Relatório mensal em PDF baixado.")}catch{setMessage("Não foi possível gerar o arquivo.")}finally{setBusy(false)}};
 const backup=async()=>{setBusy(true);try{await saveBackup();setMessage("Backup completo baixado.")}catch{setMessage("Não foi possível gerar o arquivo.")}finally{setBusy(false)}};
 const choose=(event:ChangeEvent<HTMLInputElement>)=>{const selectedFile=event.target.files?.[0]||null;setFile(selectedFile);setMessage(selectedFile?`Arquivo selecionado: ${selectedFile.name}`:"")};
 const restore=async()=>{if(!file||!confirm("Restaurar este backup substituirá todos os dados atuais. Deseja continuar?"))return;setBusy(true);try{const response=await fetch("/api/backup",{method:"POST",headers:{"content-type":"application/json"},body:await file.text()}),result=await response.json() as {error?:string;months?:number};if(!response.ok)throw new Error(result.error);setMessage(`Backup restaurado: ${result.months} meses recuperados.`);setFile(null)}catch(error){setMessage(error instanceof Error&&error.message?error.message:"Não foi possível restaurar este arquivo.")}finally{setBusy(false)}};
 const importPayload=(action:"preview"|"commit")=>({action,targetMonth,documentType,accountName,fileName:bankFile?.name||"extrato",content:importContent,selectedFingerprints:[...selected],categoryOverrides});
 const analyzeStatement=async()=>{if(!bankFile||!targetMonth)return;setBusy(true);setMessage("");setPreview(null);try{const content=await bankFile.text();setImportContent(content);const response=await fetch("/api/imports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...importPayload("preview"),content,fileName:bankFile.name})}),result=await response.json() as ImportPreview&{error?:string};if(!response.ok)throw new Error(result.error||"Não foi possível ler este extrato.");setPreview(result);setSelected(new Set(result.items.filter(item=>!item.duplicateKind).map(item=>item.fingerprint)));setCategoryOverrides(Object.fromEntries(result.items.map(item=>[item.fingerprint,item.category])))}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível ler este extrato.")}finally{setBusy(false)}};
 const commitImport=async()=>{if(!preview)return;setBusy(true);setMessage("");try{const response=await fetch("/api/imports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(importPayload("commit"))}),result=await response.json() as {error?:string;imported:number;flagged:number;skipped:number};if(!response.ok)throw new Error(result.error||"Não foi possível concluir a importação.");setMessage(`${result.imported} ${result.imported===1?"movimentação importada":"movimentações importadas"}. ${result.flagged?`${result.flagged} possível duplicidade foi enviada para a Leitura Financeira.`:"Nenhuma nova duplicidade ficou pendente."}`);setPreview(null);setBankFile(null);setImportContent("");const backupResponse=await fetch("/api/backup");if(backupResponse.ok)setInfo(await backupResponse.json())}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível concluir a importação.")}finally{setBusy(false)}};
 const toggle=(fingerprint:string)=>setSelected(current=>{const next=new Set(current);if(next.has(fingerprint))next.delete(fingerprint);else next.add(fingerprint);return next});
 const months=info?.months.length||0,expenses=info?.months.reduce((sum,month)=>sum+month.expenses.length,0)||0,jobs=info?.months.reduce((sum,month)=>sum+month.freelancers.length,0)||0,selectedTotal=useMemo(()=>preview?.items.filter(item=>selected.has(item.fingerprint)).reduce((sum,item)=>sum+item.amount,0)||0,[preview,selected]);

 return <main className="dataPage">
  <nav className="viewNav desktopViewNav"><a href="/">Visão mensal</a><a href="/resumo">Resumo anual</a><a className="active" href="/dados">Dados e backup</a><a href="/leitura">Leitura</a><a href="/metas">Metas</a></nav>
  <header className="dataHeader"><div><span className="eyebrow">SEGURANÇA E CONCILIAÇÃO</span><h1>Dados, backup e importação</h1><p>Proteja suas informações e complete o mês usando seus documentos bancários.</p></div><div className="backupStatus"><i/>Dados armazenados no site</div></header>
  <section className="backupOverview"><article><span>Meses protegidos</span><strong>{months}</strong></article><article><span>Contas registradas</span><strong>{expenses}</strong></article><article><span>Freelas registrados</span><strong>{jobs}</strong></article></section>

  <section className="bankImportPanel">
   <div className="bankImportHead"><div><span className="eyebrow">CONCILIAÇÃO BANCÁRIA</span><h2>Importar extrato ou fatura</h2><p>O Shift Zone identifica saídas, sugere categorias e compara cada movimentação com o que já foi lançado manualmente.</p></div><span className="safeImportBadge">Nada entra sem sua revisão</span></div>
   <div className="importSteps"><div><b>1</b><span>Envie OFX ou CSV</span></div><div><b>2</b><span>Confira categorias e duplicidades</span></div><div><b>3</b><span>Confirme a importação</span></div></div>
   <div className="importForm">
    <label>Tipo de documento<select value={documentType} onChange={event=>{setDocumentType(event.target.value as "bank_statement"|"credit_card");setPreview(null)}}><option value="bank_statement">Extrato bancário</option><option value="credit_card">Fatura de cartão</option></select></label>
    <label>Conta ou cartão<input placeholder="Ex.: Nubank principal" value={accountName} onChange={event=>setAccountName(event.target.value)}/></label>
    <label>Mês de destino<select value={targetMonth} onChange={event=>{setTargetMonth(event.target.value);setPreview(null)}}>{info?.months.map(month=><option key={month.monthKey} value={month.monthKey}>{monthName(month.monthKey)}</option>)}</select></label>
    <label className={`statementFile ${bankFile?"hasFile":""}`}><span>{bankFile?bankFile.name:"Selecionar arquivo OFX ou CSV"}</span><input type="file" accept=".ofx,.csv,text/csv,application/x-ofx" onChange={event=>{setBankFile(event.target.files?.[0]||null);setPreview(null)}}/></label>
    <button className="analyzeStatement" disabled={!bankFile||!targetMonth||busy} onClick={analyzeStatement}>{busy&&!preview?"Analisando…":"Analisar arquivo"}</button>
   </div>
   <p className="importPrivacy">O arquivo é lido somente para identificar as movimentações. Nesta versão, entradas como salários e Pix recebidos ficam fora da importação de gastos.</p>

   {preview&&<div className="importReview">
    <div className="reviewSummary"><div><span>Saídas encontradas</span><strong>{preview.summary.transactions}</strong></div><div><span>Prontas para importar</span><strong>{preview.summary.ready}</strong></div><div className={preview.summary.duplicates?"warn":""}><span>Possíveis duplicidades</span><strong>{preview.summary.duplicates}</strong></div><div><span>Entradas não importadas</span><strong>{preview.ignoredIncome}</strong></div></div>
    {preview.summary.duplicates>0&&<div className="duplicateNotice"><b>Encontramos lançamentos que merecem análise.</b><span>Eles começam desmarcados. Mesmo que não sejam importados novamente, a correspondência com o lançamento manual será registrada na Leitura Financeira.</span></div>}
    <div className="reviewTableWrap"><table className="reviewTable"><thead><tr><th>Importar</th><th>Data e descrição</th><th>Categoria sugerida</th><th>Valor</th><th>Análise</th></tr></thead><tbody>{preview.items.map(item=><tr key={item.fingerprint} className={item.duplicateKind?"duplicateRow":""}><td><input aria-label={`Importar ${item.description}`} type="checkbox" checked={selected.has(item.fingerprint)} disabled={item.duplicateKind==="already_imported"||item.duplicateKind==="within_file"} onChange={()=>toggle(item.fingerprint)}/></td><td><span>{new Date(item.date+"T12:00:00").toLocaleDateString("pt-BR")}</span><b>{item.description}</b></td><td><select value={categoryOverrides[item.fingerprint]||item.category} onChange={event=>setCategoryOverrides({...categoryOverrides,[item.fingerprint]:event.target.value})}>{[...new Set([item.category,...categories])].map(category=><option key={category}>{category}</option>)}</select><small>Confiança {item.confidence==="high"?"alta":item.confidence==="medium"?"média":"baixa"}</small></td><td><strong>{BRL.format(item.amount)}</strong></td><td>{item.duplicateKind?<span className="duplicateTag">Revisar</span>:<span className="readyTag">Pronto</span>}<small>{item.duplicateReason||"Nenhuma correspondência encontrada."}</small></td></tr>)}</tbody></table></div>
    <div className="reviewFooter"><div><span>{selected.size} selecionadas</span><strong>{BRL.format(selectedTotal)}</strong></div><button disabled={busy} onClick={commitImport}>{busy?"Importando…":"Confirmar importação"}</button></div>
   </div>}
  </section>

  <section className="backupGrid"><article className="backupCard primaryBackup"><span className="backupIcon">↓</span><div><span className="eyebrow">RECOMENDADO</span><h2>Backup completo</h2><p>Guarda todos os meses, rendas, contas, parcelas, pagamentos, títulos e cores.</p><ul><li>Serve para restaurar o site</li><li>Mantém todos os detalhes editáveis</li><li>Formato seguro JSON</li></ul></div><button disabled={busy} onClick={backup}>Baixar backup completo</button></article><article className="backupCard"><span className="backupIcon">▦</span><div><span className="eyebrow">PLANILHA REORGANIZADA</span><h2>Exportar para Excel</h2><p>Resumo limpo, lista individual completa e uma aba organizada para cada mês.</p><ul><li>Cada gasto aparece em uma linha</li><li>Contas organizadas pelos vencimentos personalizados</li><li>Subtotais, pagamentos e parcelas</li></ul></div><button disabled={busy||!info} onClick={()=>download("excel")}>Baixar nova planilha Excel</button></article></section>
  <section className="pdfExportPanel"><span className="pdfIcon">PDF</span><div><span className="eyebrow">RELATÓRIO MENSAL</span><h2>Exportar mês em PDF</h2><p>Um documento pronto para guardar ou compartilhar, com resumo e todas as contas organizadas por vencimento.</p></div><div className="pdfActions"><select aria-label="Mês do relatório" value={pdfMonth} onChange={event=>setPdfMonth(event.target.value)}>{info?.months.map(month=><option key={month.monthKey} value={month.monthKey}>{monthName(month.monthKey)}</option>)}</select><button disabled={busy||!pdfMonth} onClick={()=>download("pdf")}>Baixar relatório PDF</button></div></section>
  <section className="restorePanel"><div><span className="eyebrow">RESTAURAÇÃO</span><h2>Recuperar um backup</h2><p>Selecione um arquivo JSON criado pelo Shift Zone. Antes de confirmar, guarde um backup dos dados atuais.</p></div><div className="restoreActions"><label className={file?"hasFile":""}><input type="file" accept="application/json,.json" onChange={choose}/><span>{file?file.name:"Selecionar arquivo de backup"}</span></label><button disabled={!file||busy} onClick={restore}>{busy?"Aguarde…":"Restaurar dados"}</button></div></section>
  {message&&<div className="backupMessage" role="status">{message}</div>}<aside className="backupAdvice"><b>Minha recomendação</b><p>Prefira arquivos OFX. Eles trazem as movimentações de forma estruturada e reduzem erros de leitura.</p></aside>
  <nav className="mobileViewNav"><a href="/"><span>▤</span>Mês</a><a href="/resumo"><span>▥</span>Ano</a><a className="active" href="/dados"><span>↓</span>Dados</a><a href="/leitura"><span>◆</span>Leitura</a><a href="/metas"><span>◎</span>Metas</a></nav>
 </main>
}
