import {getUserId,unauthorized} from "../auth/session";
import {db} from "../supabase";
import {duePeriodFor,ExistingExpense,parseStatement,ReconciliationIssue} from "../../../lib/bankImport";

type MonthRow={month_key:string;due_periods:number[];expenses:ExistingExpense[]};
type StateRow={primary_person_name:string|null};
type Payload={action:"preview"|"commit";targetMonth:string;documentType:"bank_statement"|"credit_card";accountName:string;dueDay?:number|null;fileName:string;content:string;selectedFingerprints?:string[];categoryOverrides?:Record<string,string>;nameOverrides?:Record<string,string>;installmentOverrides?:Record<string,{current:number|null;total:number|null}>};
const validMonth=(value:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(value),filter=(value:string)=>encodeURIComponent(value);

export async function POST(req:Request){
 const userId=await getUserId(req);if(!userId)return unauthorized();let payload:Payload;try{payload=await req.json() as Payload}catch{return Response.json({error:"Arquivo inválido"},{status:400})}
 if(!["preview","commit"].includes(payload.action)||!validMonth(payload.targetMonth)||!["bank_statement","credit_card"].includes(payload.documentType)||!payload.fileName||!payload.content||payload.content.length>5_000_000)return Response.json({error:"Dados de importação inválidos"},{status:400});
 const uid=filter(userId),[rows,allRows,states]=await Promise.all([db(`finance_months?user_id=eq.${uid}&month_key=eq.${filter(payload.targetMonth)}&select=month_key,due_periods,expenses`) as Promise<MonthRow[]>,db(`finance_months?user_id=eq.${uid}&select=month_key,due_periods,expenses`) as Promise<MonthRow[]>,db(`finance_state?user_id=eq.${uid}&select=primary_person_name`) as Promise<StateRow[]>]),month=rows[0];if(!month)return Response.json({error:"O mês selecionado ainda não existe no dashboard"},{status:404});
 const knownExpenses=allRows.flatMap(row=>row.expenses||[]),parsed=parseStatement(payload.content,payload.fileName,month.expenses||[],payload.documentType,knownExpenses,payload.targetMonth),expenses=parsed.items.filter(item=>item.direction==="expense");if(!expenses.length)return Response.json({error:"Nenhuma saída válida foi encontrada. O arquivo precisa mostrar data, descrição e valor; no PDF, o texto deve ser selecionável."},{status:422});
 if(payload.action==="preview")return Response.json({items:expenses,ignoredIncome:parsed.ignoredIncome,summary:{transactions:expenses.length,duplicates:expenses.filter(item=>item.duplicateKind).length,ready:expenses.filter(item=>!item.duplicateKind||payload.documentType==="bank_statement"&&item.duplicateKind==="possible_manual").length}});
 const selected=new Set(payload.selectedFingerprints||[]),now=new Date().toISOString(),accountName=String(payload.accountName||"").trim().slice(0,80)||"Conta não informada",fileName=String(payload.fileName).replace(/[^\w.()\- áàâãéêíóôõúç]/gi,"").slice(0,120),owner=states[0]?.primary_person_name||"Titular",current=[...(month.expenses||[])],newExpenses:Record<string,unknown>[]=[];let flagged=0,skipped=0;
 for(const transaction of expenses){
  const category=String(payload.categoryOverrides?.[transaction.fingerprint]||transaction.category).trim().slice(0,60)||transaction.category;
  const name=String(payload.nameOverrides?.[transaction.fingerprint]||transaction.description).replace(/\s+/g," ").trim().slice(0,60)||transaction.description,userEditedName=name!==transaction.description&&!transaction.nameLearned;
  if(transaction.duplicateKind==="already_imported"||transaction.duplicateKind==="within_file"){skipped++;continue}
  if(transaction.duplicateKind==="possible_manual"&&transaction.matchedExpenseId!=null){const index=current.findIndex(item=>String(item.id)===String(transaction.matchedExpenseId));if(index>=0){const issue:ReconciliationIssue={fingerprint:transaction.fingerprint,date:transaction.date,description:name,amount:transaction.amount,category,accountName,fileName,detectedAt:now,status:"pending"},issues=current[index].reconciliationIssues||[];if(!issues.some(item=>item.fingerprint===issue.fingerprint)){current[index]={...current[index],reconciliationIssues:[...issues,issue]};flagged++}}}
  if(!selected.has(transaction.fingerprint)){skipped++;continue}
  const isMovement=payload.documentType==="bank_statement",override=payload.installmentOverrides?.[transaction.fingerprint],candidateCurrent=Number(override?.current??transaction.installmentCurrent),candidateTotal=Number(override?.total??transaction.installmentTotal),isInstallment=!isMovement&&Number.isInteger(candidateCurrent)&&Number.isInteger(candidateTotal)&&candidateCurrent>=1&&candidateTotal>=2&&candidateCurrent<=candidateTotal,installmentCurrent=isInstallment?candidateCurrent:null,installmentTotal=isInstallment?candidateTotal:null,configuredDue=Number(payload.dueDay),[targetYear,targetMonthNumber]=payload.targetMonth.split("-").map(Number),daysInTarget=new Date(targetYear,targetMonthNumber,0).getDate(),validConfiguredDue=!isMovement&&Number.isInteger(configuredDue)&&configuredDue>=1&&configuredDue<=daysInTarget,period=validConfiguredDue?String(configuredDue):duePeriodFor(transaction.date,month.due_periods||[10]);
  newExpenses.push({id:Date.now()+newExpenses.length,name,rawDescription:transaction.rawDescription,merchantKey:transaction.merchantKey,userEditedName:userEditedName||transaction.nameLearned,paymentMethod:transaction.paymentMethod,amount:transaction.amount,type:isMovement?"Movimentação":isInstallment?"Parcela":"Variável",recordKind:isMovement?"bank_movement":"expense",category,categoryConfidence:transaction.confidence,owner,note:`Importado de ${accountName} • ${fileName}`,confirmed:transaction.duplicateKind?false:true,period,paymentStatus:isMovement?"paid":"pending",paidDate:isMovement?transaction.date:"",transactionDate:transaction.date,installmentCurrent,installmentTotal,source:"bank_import",importInfo:{fingerprint:transaction.fingerprint,accountName,fileName,documentType:payload.documentType,importedAt:now},possibleDuplicateOf:transaction.matchedExpenseId});
 }
 const selectedDue=Number(payload.dueDay),duePeriods=payload.documentType==="credit_card"&&Number.isInteger(selectedDue)&&selectedDue>=1&&selectedDue<=new Date(Number(payload.targetMonth.slice(0,4)),Number(payload.targetMonth.slice(5,7)),0).getDate()?[...new Set([...(month.due_periods||[10]),selectedDue])].sort((a,b)=>a-b):month.due_periods||[10];
 await db(`finance_months?user_id=eq.${uid}&month_key=eq.${filter(payload.targetMonth)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({due_periods:duePeriods,expenses:[...current,...newExpenses],updated_at:now})});
 return Response.json({ok:true,imported:newExpenses.length,flagged,skipped});
}
