import {getUserId,unauthorized} from "../auth/session";
import {db} from "../supabase";
import {cleanMerchantName,detectPaymentMethod,merchantIdentity} from "../../../lib/bankImport";

type Movement={id:number|string;recordKind?:string;name?:string;rawDescription?:string;merchantKey?:string;userEditedName?:boolean;paymentMethod?:string;amount?:number;category?:string;transactionDate?:string;paidDate?:string;possibleDuplicateOf?:number|string|null;importInfo?:{accountName?:string;fileName?:string;documentType?:string}};
type MonthRow={month_key:string;expenses:Movement[]};
type StateRow={theme_bg:string;theme_accent:string;theme_surface:string};
const filter=(value:string)=>encodeURIComponent(value),validMonth=(value:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(value);

export async function GET(req:Request){const userId=await getUserId(req);if(!userId)return unauthorized();const uid=filter(userId),url=new URL(req.url),[rows,states]=await Promise.all([db(`finance_months?user_id=eq.${uid}&select=month_key,expenses&order=month_key.asc`) as Promise<MonthRow[]>,db(`finance_state?user_id=eq.${uid}&select=theme_bg,theme_accent,theme_surface`) as Promise<StateRow[]>]),months=rows.map(row=>row.month_key),requested=url.searchParams.get("month")||"",monthKey=validMonth(requested)&&months.includes(requested)?requested:months.at(-1)||"",row=rows.find(item=>item.month_key===monthKey),isMovement=(item:Movement)=>item.recordKind==="bank_movement"||item.importInfo?.documentType==="bank_statement",movements=(row?.expenses||[]).filter(isMovement).map(item=>{const raw=item.rawDescription||item.name||"Movimentação bancária";return {...item,name:item.userEditedName&&item.name?.trim()?item.name.trim():cleanMerchantName(raw),merchantKey:item.merchantKey||merchantIdentity(raw),paymentMethod:item.paymentMethod||detectPaymentMethod(raw,"bank_statement"),transactionDate:item.transactionDate||item.paidDate||`${monthKey}-01`}}).sort((a,b)=>String(b.transactionDate||"").localeCompare(String(a.transactionDate||""))),state=states[0];return Response.json({monthKey,months,movements,profile:{themeBg:state?.theme_bg||"#030504",themeAccent:state?.theme_accent||"#2f9d6f",themeSurface:state?.theme_surface||"#0d110f"}})}

export async function PATCH(req:Request){const userId=await getUserId(req);if(!userId)return unauthorized();const payload=await req.json() as {monthKey:string;id:number|string;name:string};const name=String(payload.name||"").replace(/\s+/g," ").trim().slice(0,60);if(!validMonth(payload.monthKey)||payload.id==null||name.length<2)return Response.json({error:"Informe um nome válido"},{status:400});const uid=filter(userId),rows=await db(`finance_months?user_id=eq.${uid}&month_key=eq.${filter(payload.monthKey)}&select=expenses`) as MonthRow[],row=rows[0];if(!row)return Response.json({error:"Mês não encontrado"},{status:404});const isMovement=(item:Movement)=>item.recordKind==="bank_movement"||item.importInfo?.documentType==="bank_statement",target=(row.expenses||[]).find(item=>isMovement(item)&&String(item.id)===String(payload.id));if(!target)return Response.json({error:"Movimentação não encontrada"},{status:404});const raw=target.rawDescription||target.name||"",merchantKey=target.merchantKey||merchantIdentity(raw),expenses=(row.expenses||[]).map(item=>{const itemRaw=item.rawDescription||item.name||"",itemKey=item.merchantKey||merchantIdentity(itemRaw);return isMovement(item)&&itemKey===merchantKey?{...item,name,merchantKey,userEditedName:true}:item});await db(`finance_months?user_id=eq.${uid}&month_key=eq.${filter(payload.monthKey)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({expenses,updated_at:new Date().toISOString()})});return Response.json({ok:true,name,merchantKey})}

export async function DELETE(req:Request){const userId=await getUserId(req);if(!userId)return unauthorized();const payload=await req.json() as {monthKey:string;id:number|string};if(!validMonth(payload.monthKey)||payload.id==null)return Response.json({error:"Dados inválidos"},{status:400});const uid=filter(userId),rows=await db(`finance_months?user_id=eq.${uid}&month_key=eq.${filter(payload.monthKey)}&select=expenses`) as MonthRow[],row=rows[0];if(!row)return Response.json({error:"Mês não encontrado"},{status:404});const expenses=(row.expenses||[]).filter(item=>!((item.recordKind==="bank_movement"||item.importInfo?.documentType==="bank_statement")&&String(item.id)===String(payload.id)));await db(`finance_months?user_id=eq.${uid}&month_key=eq.${filter(payload.monthKey)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({expenses,updated_at:new Date().toISOString()})});return Response.json({ok:true})}
