"use client";
import {useEffect,useMemo,useState} from "react";

type AnnualMonth={monthKey:string;fixedIncome:number;freelance:number;totalIncome:number;expenses:number;balance:number;paid:number;pending:number;installments:number;endingInstallments:number};
type AnnualData={brand:string;heading:string;subtitle:string;themeBg:string;themeAccent:string;themeSurface:string;year:string;years:string[];months:AnnualMonth[]};
const BRL=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const shortMonth=(key:string)=>new Intl.DateTimeFormat("pt-BR",{month:"short",timeZone:"UTC"}).format(new Date(`${key}-01T00:00:00Z`)).replace(".","").replace(/^./,c=>c.toUpperCase());
const fontFamilies:Record<string,string>={modern:'Inter,"Segoe UI",system-ui,sans-serif',geometric:'"Avenir Next","Trebuchet MS","Segoe UI",sans-serif',rounded:'ui-rounded,"Arial Rounded MT Bold","Trebuchet MS",sans-serif'};

export default function AnnualSummary(){
 const [data,setData]=useState<AnnualData|null>(null),[year,setYear]=useState("2026"),[loading,setLoading]=useState(true);
 const load=async(selected:string)=>{setLoading(true);try{const response=await fetch(`/api/finances?summary=annual&year=${selected}`);if(!response.ok)throw 0;const result=await response.json() as AnnualData;setData(result);setYear(result.year);document.documentElement.style.setProperty("--user-bg",result.themeBg);document.documentElement.style.setProperty("--user-accent",result.themeAccent);document.documentElement.style.setProperty("--user-surface",result.themeSurface);localStorage.setItem("dashfinance-bg",result.themeBg);localStorage.setItem("dashfinance-accent",result.themeAccent);localStorage.setItem("dashfinance-surface",result.themeSurface);const font=localStorage.getItem("dashfinance-font")||"modern";document.documentElement.style.setProperty("--user-display-font",fontFamilies[font]||fontFamilies.modern)}finally{setLoading(false)}};
 useEffect(()=>{load(new URLSearchParams(window.location.search).get("year")||"2026")},[]);
 const totals=useMemo(()=>data?.months.reduce((sum,m)=>({income:sum.income+m.totalIncome,expenses:sum.expenses+m.expenses,freelance:sum.freelance+m.freelance,balance:sum.balance+m.balance,paid:sum.paid+m.paid,pending:sum.pending+m.pending}),{income:0,expenses:0,freelance:0,balance:0,paid:0,pending:0})||{income:0,expenses:0,freelance:0,balance:0,paid:0,pending:0},[data]);
 const max=Math.max(1,...(data?.months.flatMap(m=>[m.totalIncome,m.expenses])||[])),best=data?.months.reduce((a,b)=>b.balance>a.balance?b:a,data.months[0]),worst=data?.months.reduce((a,b)=>b.balance<a.balance?b:a,data.months[0]),activeInstallments=data?.months.at(-1)?.installments||0;
 return <main className="annualPage">
  <nav className="viewNav desktopViewNav" aria-label="Área do dashboard"><a href="/">Visão mensal</a><a className="active" href="/resumo">Resumo anual</a><a href="/dados">Dados e backup</a><a href="/leitura">Leitura</a></nav>
  <header className="annualHeader"><div><span className="eyebrow">{data?.brand||"MYFINANCE"} · VISÃO DO ANO</span><h1>Resumo anual</h1><p>Uma leitura simples da evolução financeira da família.</p></div><label className="yearPicker">ANO<select value={year} onChange={e=>load(e.target.value)} disabled={loading}>{(data?.years.length?data.years:[year]).map(y=><option key={y}>{y}</option>)}</select></label></header>
  <section className="annualMetrics"><article className="featured"><span>Saldo acumulado</span><strong>{BRL.format(totals.balance)}</strong><small>{totals.income?`${(totals.expenses/totals.income*100).toFixed(1).replace(".",",")}% da renda comprometida no ano`:"Aguardando meses cadastrados"}</small></article><article><span>Renda total</span><strong>{BRL.format(totals.income)}</strong><small>Fixo + trabalhos extras</small></article><article><span>Gastos do ano</span><strong>{BRL.format(totals.expenses)}</strong><small>{BRL.format(totals.paid)} já pagos</small></article><article><span>Freelancers</span><strong>{BRL.format(totals.freelance)}</strong><small>Renda variável acumulada</small></article></section>
  {data?.months.length?<><section className="annualGrid"><article className="annualPanel chartPanel"><div className="panelTitle"><div><span className="eyebrow">COMPARAÇÃO MENSAL</span><h2>Entradas x gastos</h2></div><div className="legend"><i className="incomeKey"/>Renda <i className="expenseKey"/>Gastos</div></div><div className="annualChart">{data.months.map(m=><a href={`/?month=${m.monthKey}`} className="chartRow" key={m.monthKey}><b>{shortMonth(m.monthKey)}</b><div><span className="incomeBar" style={{width:`${m.totalIncome/max*100}%`}}/><span className="expenseBar" style={{width:`${m.expenses/max*100}%`}}/></div><strong>{BRL.format(m.balance)}</strong></a>)}</div></article><article className="annualPanel insightPanel"><span className="eyebrow">DESTAQUES DO ANO</span><h2>O que merece atenção</h2><div className="annualHighlights"><div><span>Melhor saldo</span><b>{best?shortMonth(best.monthKey):"—"}</b><strong>{best?BRL.format(best.balance):"—"}</strong></div><div><span>Menor saldo</span><b>{worst?shortMonth(worst.monthKey):"—"}</b><strong>{worst?BRL.format(worst.balance):"—"}</strong></div><div><span>Parcelas ativas</span><b>{activeInstallments}</b><strong>No mês mais recente</strong></div><div><span>Ainda pendente</span><b>{BRL.format(totals.pending)}</b><strong>Nas contas cadastradas</strong></div></div></article></section><section className="annualPanel monthOverview"><div className="panelTitle"><div><span className="eyebrow">HISTÓRICO</span><h2>Todos os meses</h2></div><small>Toque em um mês para abrir a agenda completa</small></div><div className="monthOverviewGrid">{data.months.map(m=><a href={`/?month=${m.monthKey}`} key={m.monthKey}><div><b>{shortMonth(m.monthKey)}</b><span>{m.installments} parcelas ativas</span></div><strong className={m.balance<0?"negative":""}>{BRL.format(m.balance)}</strong><i>→</i></a>)}</div></section></>:<section className="annualEmpty"><b>{loading?"Carregando resumo…":"Ainda não há meses neste ano"}</b><p>Crie um período na visão mensal para começar o histórico anual.</p><a href="/">Ir para visão mensal</a></section>}
  <nav className="mobileViewNav" aria-label="Área do dashboard"><a href="/"><span>▤</span>Mês</a><a className="active" href="/resumo"><span>▥</span>Ano</a><a href="/dados"><span>↓</span>Dados</a><a href="/leitura"><span>◆</span>Leitura</a></nav>
 </main>
}
