"use client";
import {useEffect,useMemo,useState} from "react";

type Movement={id:number|string;name:string;paymentMethod:string;amount:number;category:string;transactionDate:string;possibleDuplicateOf?:number|string|null;importInfo?:{accountName?:string;fileName?:string}};
type Data={monthKey:string;months:string[];movements:Movement[];profile:{themeBg:string;themeAccent:string;themeSurface:string}};
const BRL=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const monthName=(key:string)=>new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${key}-01T00:00:00Z`)).replace(/^./,letter=>letter.toUpperCase());
const dateName=(date:string)=>new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"short"}).format(new Date(`${date}T12:00:00`)).replace(/^./,letter=>letter.toUpperCase());

export default function Movements(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const load=async(month?:string)=>{setLoading(true);setMessage("");try{const response=await fetch(`/api/movements${month?`?month=${month}`:""}`);if(!response.ok)throw new Error();const result:Data=await response.json();setData(result);document.documentElement.style.setProperty("--user-bg",result.profile.themeBg);document.documentElement.style.setProperty("--user-accent",result.profile.themeAccent);document.documentElement.style.setProperty("--user-surface",result.profile.themeSurface)}catch{setMessage("Não foi possível carregar as movimentações.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const remove=async(movement:Movement)=>{if(!data||!confirm(`Remover a movimentação “${movement.name}”?`))return;const response=await fetch("/api/movements",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({monthKey:data.monthKey,id:movement.id})});if(response.ok)setData({...data,movements:data.movements.filter(item=>String(item.id)!==String(movement.id))});else setMessage("Não foi possível remover esta movimentação.")};
 const grouped=useMemo(()=>{const result=new Map<string,Movement[]>();for(const movement of data?.movements||[]){const key=movement.transactionDate||data?.monthKey+"-01";result.set(key,[...(result.get(key)||[]),movement])}return [...result.entries()]},[data]),total=data?.movements.reduce((sum,item)=>sum+Number(item.amount||0),0)||0,pix=data?.movements.filter(item=>item.paymentMethod==="Pix")||[],card=data?.movements.filter(item=>item.paymentMethod==="Cartão de débito")||[];
 return <main className="movementsPage">
  <nav className="viewNav desktopViewNav" aria-label="Área do dashboard"><a href="/">Visão mensal</a><a className="active" href="/movimentacoes">Movimentações</a><a href="/resumo">Resumo anual</a><a href="/dados">Dados e backup</a><a href="/leitura">Leitura</a><a href="/metas">Metas</a></nav>
  <header className="movementsHeader"><div><span className="eyebrow">DINHEIRO QUE JÁ SAIU</span><h1>Movimentações da conta</h1><p>Pix, débitos e pagamentos realizados ficam aqui, separados das dívidas que ainda serão pagas.</p></div>{data&&<select aria-label="Selecionar mês" value={data.monthKey} onChange={event=>load(event.target.value)}>{data.months.map(month=><option key={month} value={month}>{monthName(month)}</option>)}</select>}</header>
  <section className="movementMetrics"><article className="featured"><span>Total movimentado</span><strong>{BRL.format(total)}</strong><small>{data?.movements.length||0} saídas registradas</small></article><article><span>Pagamentos via Pix</span><strong>{BRL.format(pix.reduce((sum,item)=>sum+item.amount,0))}</strong><small>{pix.length} movimentações</small></article><article><span>Cartão de débito</span><strong>{BRL.format(card.reduce((sum,item)=>sum+item.amount,0))}</strong><small>{card.length} movimentações</small></article></section>
  {message&&<div className="movementMessage">{message}</div>}
  {loading?<div className="movementsEmpty">Carregando movimentações…</div>:!data?.movements.length?<section className="movementsEmpty"><b>Nenhuma saída importada neste mês</b><p>Importe um extrato OFX ou CSV. Pagamentos já realizados aparecerão aqui e não aumentarão suas dívidas.</p><a href="/dados">Importar extrato bancário</a></section>:<section className="movementTimeline">{grouped.map(([date,items])=><article className="movementDay" key={date}><div className="movementDayHead"><span>{dateName(date)}</span><strong>{BRL.format(items.reduce((sum,item)=>sum+item.amount,0))}</strong></div><div className="movementList">{items.map(item=><div className="movementRow" key={item.id}><span className="movementMethod">{item.paymentMethod==="Pix"?"PX":item.paymentMethod==="Cartão de débito"?"DB":"$"}</span><div className="movementIdentity"><b>{item.name}</b><span>{item.paymentMethod} · {item.category}</span></div><div className="movementOrigin"><span>{item.importInfo?.accountName||"Conta importada"}</span>{item.possibleDuplicateOf&&<i>Verificar correspondência</i>}</div><strong>{BRL.format(item.amount)}</strong><button aria-label={`Remover ${item.name}`} onClick={()=>remove(item)}>×</button></div>)}</div></article>)}</section>}
  <p className="movementFootnote">As movimentações representam pagamentos já realizados. Elas não entram novamente no total de dívidas do mês.</p>
  <nav className="mobileViewNav movementsMobileNav" aria-label="Área do dashboard"><a href="/"><span>▤</span>Mês</a><a className="active" href="/movimentacoes"><span>↕</span>Mov.</a><a href="/resumo"><span>▥</span>Ano</a><a href="/dados"><span>↓</span>Dados</a><a href="/leitura"><span>◆</span>Leitura</a><a href="/metas"><span>◎</span>Metas</a></nav>
 </main>
}
